# Generated by Django 3.2.25 on 2024-05-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EuroMillionsResult',
        ),
    ]
