# Generated by Django 3.2.25 on 2024-05-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraping', '0002_delete_euromillionsresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuroMillionsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.CharField(max_length=10)),
                ('ball_1', models.IntegerField()),
                ('ball_2', models.IntegerField()),
                ('ball_3', models.IntegerField()),
                ('ball_4', models.IntegerField()),
                ('ball_5', models.IntegerField()),
                ('lucky_star_1', models.IntegerField()),
                ('lucky_star_2', models.IntegerField()),
            ],
        ),
    ]
