# Generated by Django 3.2.25 on 2024-05-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_euromillionsresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='euromillionsresult',
            name='jackpot',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='euromillionsresult',
            name='prize_breakdown',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
