# Generated by Django 4.2.11 on 2024-05-13 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('subscribe_stats', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('subscribe_stats_date', models.DateField(blank=True, null=True)),
                ('subscribe_stats_date_expiry', models.DateField(blank=True, null=True)),
                ('subscribe_stats_cancel_date', models.DateField(blank=True, null=True)),
                ('subscribe_predictions', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('subscribe_predictions_date', models.DateField(blank=True, null=True)),
                ('subscribe_predictions_date_expiry', models.DateField(blank=True, null=True)),
                ('subscribe_predictions_cancel_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
