# Generated by Django 4.2.11 on 2024-05-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price',
        ),
    ]
