# Generated by Django 4.2.11 on 2024-05-16 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subscribe_type', models.CharField(choices=[('STA', 'Statistics'), ('PRE', 'Predictions'), ('FUL', 'Full Subscription'), ('SEL', 'Select')], default='SEL', max_length=3)),
                ('subscribe_end_date', models.DateField(blank=True, null=True)),
                ('subscribe_cancel_date', models.DateField(blank=True, null=True)),
                ('subscribe_renewal_date', models.DateField(blank=True, null=True)),
                ('subscribe_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
