# Generated by Django 4.2.11 on 2024-05-26 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('STA', 'Statistics'), ('PRE', 'Predictions'), ('FUL', 'Full Subscription'), ('SEL', 'Select')], max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subscribe_end_date', models.DateField(blank=True, null=True)),
                ('subscribe_cancel_date', models.DateField(blank=True, null=True)),
                ('subscribe_renewal_date', models.DateField(blank=True, null=True)),
                ('subscribe_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subscription_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.subscriptiontype')),
            ],
        ),
    ]
