# Generated by Django 4.2.11 on 2024-05-18 06:42

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_subscriptiontype_remove_subscription_subscribe_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
