# Generated by Django 4.2.11 on 2024-06-01 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_subscriptiontype_subscription_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
