# Generated by Django 4.2.11 on 2024-06-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_subscription_subscription_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='recurring_subscription',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscribe_cancel_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscribe_end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscribe_price',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscribe_renewal_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_start_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='trial_price',
        ),
        migrations.AddField(
            model_name='subscription',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='prod_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
