# Generated by Django 4.2.11 on 2024-06-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_subscription_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='recurring_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
