# Generated by Django 4.2.11 on 2024-06-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_subscription_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
