# Generated by Django 4.2.11 on 2024-06-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_subscription_cancelled_on"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SubscriptionType",
        ),
    ]
